export const ROUTES = {
  account: "/account",
  academy: "/academy",
  academyCertificates: "/academy/certificates",
  academyLearningPaths: "/academy/learning-paths",
  analysis: "/analysis",
  alerts: "/alerts",
  assistant: "/assistant",
  charts: "/charts",
  api: {
    newsletter: "/api/newsletter",
    revolutWebhook: "/api/webhooks/revolut",
  },
  auth: {
    callback: "/auth/callback",
    confirm: "/auth/confirm",
    forgotPassword: "/forgot-password",
    login: "/login",
    register: "/register",
    resetPassword: "/reset-password",
  },
  billing: "/account/billing",
  dashboard: "/dashboard",
  dashboardCertificates: "/dashboard/learning/certificates",
  dashboardLearningPaths: "/dashboard/learning/paths",
  dashboardLearningRecommendations: "/dashboard/learning/recommendations",
  dashboardLearningNotifications: "/dashboard/learning/notifications",
  economicCalendar: "/economic-calendar",
  home: "/",
  membership: {
    cancelled: "/membership/cancelled",
    pending: "/membership/pending",
    success: "/membership/success",
  },
  newsletter: "/#newsletter",
  premium: "/premium",
  watchlists: "/watchlists",
  webinars: "/webinars",
} as const;
