-- DayTradingPost market-data snapshot cache.
-- Run this complete file in the Supabase SQL Editor. Do not paste the file path.

create table if not exists public.market_data_snapshots (
  id bigint generated by default as identity primary key,
  instrument_slug text not null,
  symbol text not null,
  price numeric not null,
  currency text not null,
  previous_close numeric,
  change numeric,
  change_percent numeric,
  day_high numeric,
  day_low numeric,
  market_status text not null check (
    market_status in ('open', 'closed', 'premarket', 'afterhours', 'unavailable', 'unknown')
  ),
  provider text not null,
  provider_timestamp timestamptz,
  received_at timestamptz not null default now(),
  delayed boolean not null default false,
  delay_minutes integer check (delay_minutes is null or delay_minutes >= 0),
  created_at timestamptz not null default now(),
  constraint market_data_snapshots_instrument_slug_not_blank
    check (length(trim(instrument_slug)) > 0),
  constraint market_data_snapshots_provider_not_blank
    check (length(trim(provider)) > 0)
);

create index if not exists market_data_snapshots_instrument_time_idx
  on public.market_data_snapshots (instrument_slug, provider_timestamp desc);

create index if not exists market_data_snapshots_provider_time_idx
  on public.market_data_snapshots (provider, provider_timestamp desc);

alter table public.market_data_snapshots enable row level security;

-- Browser clients have no direct access. Server-side service-role operations bypass RLS.
revoke all on table public.market_data_snapshots from anon, authenticated;
revoke all on sequence public.market_data_snapshots_id_seq from anon, authenticated;

comment on table public.market_data_snapshots is
  'Short-lived server-side cache of verified, non-simulated provider quotes.';

-- Retention guidance: schedule this statement with a trusted server or pg_cron.
-- delete from public.market_data_snapshots where created_at < now() - interval '7 days';
